# Generated by Django 2.1.1 on 2018-09-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_amerika', models.IntegerField(verbose_name='Codigo de Amerika')),
                ('serial', models.CharField(blank=True, max_length=30, verbose_name='Numero de serie')),
                ('observation', models.CharField(blank=True, max_length=30, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima edición')),
            ],
            options={
                'verbose_name': 'equipoInv',
                'verbose_name_plural': 'equiposInv',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iventory_date', models.DateField(verbose_name='Fecha')),
                ('status_open', models.BooleanField(default=True, verbose_name='Activar inventario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima edición')),
            ],
            options={
                'verbose_name': 'inventario',
                'verbose_name_plural': 'inventarios',
                'ordering': ['-created'],
            },
        ),
    ]
