# Generated by Django 2.1.1 on 2018-09-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_auto_20180909_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='iventory_date',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
