# Generated by Django 2.1.1 on 2018-09-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_auto_20180909_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status_open',
            field=models.BooleanField(default=True),
        ),
    ]
