# Generated by Django 2.1.1 on 2018-09-10 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0009_auto_20180909_1829'),
        ('logistica', '0004_inventory_status_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='headquarter_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entidades.Headquarter', verbose_name='Nombre de la sede'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status_open',
            field=models.BooleanField(default=True, verbose_name='Activar inventario'),
        ),
    ]
