# Generated by Django 2.1.1 on 2018-09-10 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0010_auto_20180909_1841'),
        ('logistica', '0005_auto_20180909_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='department_nam',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='entidades.Department', verbose_name='nombre del departaamento'),
            preserve_default=False,
        ),
    ]
