# Generated by Django 2.1.1 on 2018-09-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0007_auto_20180909_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_amerika', models.CharField(max_length=25, verbose_name='Codigo de Amerika')),
                ('serial', models.CharField(max_length=30, null=True, verbose_name='Numero de serie')),
                ('status', models.CharField(choices=[('A', 'Activo'), ('R', 'Reparacion'), ('D', 'Danado')], max_length=1)),
                ('observation', models.TextField(verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima edición')),
            ],
        ),
    ]
