# Generated by Django 2.1.1 on 2018-09-10 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0008_equipmentinv'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinv',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logistica.Inventory', verbose_name='Inventario'),
            preserve_default=False,
        ),
    ]
