# Generated by Django 2.1.1 on 2018-09-10 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0014_auto_20180909_2105'),
        ('logistica', '0009_equipmentinv_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinv',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entidades.Project', verbose_name='proyecto'),
            preserve_default=False,
        ),
    ]
