# Generated by Django 2.1.1 on 2018-09-10 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0017_auto_20180909_2114'),
        ('logistica', '0010_equipmentinv_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinv',
            name='type_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entidades.Type', verbose_name='proyecto'),
            preserve_default=False,
        ),
    ]
