# Generated by Django 2.1.1 on 2018-09-10 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0017_auto_20180909_2114'),
        ('logistica', '0011_equipmentinv_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinv',
            name='brand_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entidades.Brand', verbose_name='tipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentinv',
            name='employee_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entidades.Employee', verbose_name='tipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentinv',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.Type', verbose_name='tipo'),
        ),
    ]
