# Generated by Django 2.1.1 on 2018-09-10 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0012_auto_20180909_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinv',
            name='brand_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.Brand', verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='equipmentinv',
            name='employee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.Employee', verbose_name='empleado'),
        ),
    ]
