# Generated by Django 2.1.1 on 2018-09-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0013_auto_20180909_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentinv',
            options={'ordering': ['-created'], 'verbose_name': 'equipoinv', 'verbose_name_plural': 'equiposinv'},
        ),
        migrations.AlterField(
            model_name='equipmentinv',
            name='cod_amerika',
            field=models.IntegerField(verbose_name='Codigo de Amerika'),
        ),
    ]
