# Generated by Django 2.1.1 on 2018-09-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0014_auto_20180909_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinv',
            name='observation',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='equipmentinv',
            name='serial',
            field=models.CharField(blank=True, default=1, max_length=30, verbose_name='Numero de serie'),
            preserve_default=False,
        ),
    ]
