# Generated by Django 2.1.1 on 2018-09-10 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0015_auto_20180909_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentinv',
            old_name='type_name',
            new_name='t_name',
        ),
    ]
