# Generated by Django 2.1.1 on 2018-09-10 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0016_auto_20180909_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentinv',
            options={'ordering': ['-created'], 'verbose_name': 'equipoInv', 'verbose_name_plural': 'equiposInv'},
        ),
    ]
