# Generated by Django 2.1.1 on 2018-09-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0007_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.IntegerField(max_length=10, verbose_name='Codigo empleado'),
        ),
    ]
