# Generated by Django 2.1.1 on 2018-09-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0009_auto_20180909_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.IntegerField(max_length=10, verbose_name='Codigo empleado'),
        ),
    ]
