# Generated by Django 2.1.1 on 2018-09-10 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0011_department_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='p',
        ),
    ]
