# Generated by Django 2.1.1 on 2018-09-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0012_remove_department_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.IntegerField(verbose_name='Codigo empleado'),
        ),
    ]
